spring:
  mail:
    host: 10.33.22.101
    username: BU22MES
    password: 123456
    port: 587
    protocol: smtp
  quartz:
    scheduler-name: test-quartz
    job-store-type: jdbc # 使用集群模式，所以采用数据库存储
    overwrite-existing-jobs: true
    jdbc:
      initialize-schema: never # 第一次执行为always，后续为never
#      comment-prefix: #
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org.quartz.threadPool.threadCount: 4
      org.quartz.threadPool.threadPriority: 5
      org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true
      org.quartz.jobStore.misfireThreshold: 5000
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      # 在调度流程的第一步，也就是拉取待即将触发的triggers时，是上锁的状态，即不会同时存在多个线程拉取到相同的trigger的情况，也就避免的重复调度的危险。参考：https://segmentfault.com/a/1190000015492260
      org.quartz.jobStore.acquireTriggersWithinLock: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.67.72.153:3306/quartz?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    hikari:                                 # 默认配置可以查看 HikariConfig
      pool-name: hikariCP
      minimum-idle: 2                      # 最小连接数
      maximum-pool-size: 5                 # 最大连接数
      auto-commit: true                     # 自动提交
      idle-timeout: 30000                   # 连接超时的最大时长(毫秒),超时则被释放(retried),默认10分钟
      max-lifetime: 1800000
      connection-timeout: 30000             # 等待连接池分配连接的最大时长(毫秒),超过这个时长还没有获取可用的连接，则发生SQLException，默认30秒
      connection-test-query: SELECT 1



#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
